[tool.poetry]
name = "gen-options-with-branches"
version = "0.1.0"
description = ""
authors = ["Galina N <silko_gy@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
